FROM ruby:2.6.6

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

RUN mkdir /app

WORKDIR /app

COPY Gemfile /app/Gemfile

COPY Gemfile.lock /app/Gemfile.lock

RUN gem install bundler -v 2.2.11

RUN bundle install

COPY . /app

COPY docker/app/*.sh /scripts/

RUN chmod a+x /scripts/*.sh
